apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: argocd
spec:
  interval: 30m
  chart:
    spec:
      chart: gatekeeper
      version: ">=3.17.0"
      sourceRef: {kind: HelmRepository, name: gatekeeper, namespace: argocd}
  values:
    controllerManager:
      resources: {requests: {memory: 30Mi}, limits: {memory: 60Mi}}
