apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pocket-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:clemuscle/pocket-gitops.git
    targetRevision: master
    path: clusters/pocket/base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
