apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: ">=4.10.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system

  install:
    remediation:
      disableWait: true      # ← c’est ICI maintenant
      retries: 1             #   (optionnel)
    timeout: 10m

  upgrade:
    remediation:
      disableWait: true
      retries: 1
    timeout: 10m

  values:
    controller:
      service:
        type: NodePort    # on force NodePort pour Minikube
      replicaCount: 1
      resources:
        requests:
          cpu: 50m
          memory: 90Mi
        limits:
          memory: 180Mi
