apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata: {name: argo-rollouts, namespace: flux-system}
spec:
  interval: 30m
  chart:
    spec:
      chart: argo-rollouts
      version: ">=2.35.0"
      sourceRef: {kind: HelmRepository, name: argo, namespace: flux-system}
  values:
    controller:
      resources: {requests: {memory: 60Mi}, limits: {memory: 120Mi}}
