name: build-sign-publish
on:
  push:
    paths: ["apps/demo/**"]
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: {packages: write, id-token: write, contents: read}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/${{ github.repository_owner }}/demo:${{ github.sha }} apps/demo
      - uses: aquasecurity/trivy-action@0.19.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/demo:${{ github.sha }}
          exit-code: "1"
          severity: "CRITICAL,HIGH"
      - uses: sigstore/cosign-installer@v3
      - run: cosign sign --yes ghcr.io/${{ github.repository_owner }}/demo:${{ github.sha }}
      - run: docker push ghcr.io/${{ github.repository_owner }}/demo:${{ github.sha }}
